# Generated by Django 3.1.3 on 2022-06-18 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_question_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='view_count',
        ),
    ]
