# Generated by Django 3.1.3 on 2022-06-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0008_remove_question_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='view_count',
            field=models.TextField(default='0'),
        ),
    ]
